language: python
python:
  - "3.6"
before_install:
  - pip3 install termcolor
  - pip install pytest pytest-cov
  - pip install install coveralls
  - pip install coverage
script:
  - coverage run -m pytest
after_success:
  - coveralls